openapi: 3.0.3
info:
  title: Simple Ecommerce
  description: This is a RESTful API documentation.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      tags:
        - Default
      summary: Root
      responses:
        200:
          $ref: "#/components/responses/200"
  /health:
    get:
      tags:
        - Default
      summary: Health Check
      responses:
        200:
          $ref: "#/components/responses/200"
        500:
          $ref: "#/components/responses/500"
  /auth/sign-in:
    post:
      tags:
        - Auth
      summary: Sign in
      requestBody:
        $ref: "#/components/requestBodies/authSignIn"
      responses:
        200:
          $ref: "#/components/responses/authSignIn"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"
  /auth/sign-out:
    delete:
      tags:
        - Auth
      summary: Sign out
      security:
        - authorize: []
      responses:
        200:
          $ref: "#/components/responses/200"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
  /product:
    get:
      tags:
        - Product
      summary: List
      security:
        - authorize: []
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/limit"
      responses:
        200:
          $ref: "#/components/responses/productList"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - Product
      summary: Create Product
      security:
        - authorize: []
      requestBody:
        $ref: "#/components/requestBodies/productCreate"
      responses:
        200:
          $ref: "#/components/responses/200"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"  
  /product/{id}:
    get:
      tags:
        - Product
      summary: Detail
      security:
        - authorize: []
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          $ref: "#/components/responses/productDetail"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"  
    put:
      tags:
        - Product
      summary: Update
      security:
        - authorize: []
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        $ref: "#/components/requestBodies/productUpdate"
      responses:
        200:
          $ref: "#/components/responses/200"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
  /cart:
    get:
      tags:
        - Cart
      summary: List
      security:
        - authorize: []
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/limit"
      responses:
        200:
          $ref: "#/components/responses/cartList"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - Cart
      summary: Create
      security:
        - authorize: []
      requestBody:
        $ref: "#/components/requestBodies/cartCreate"
      responses:
        200:
          $ref: "#/components/responses/200"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"      
components:
  securitySchemes:
    authorize:
      type: http
      scheme: bearer
  parameters:
    id:
      in: path
      name: id
      schema:
        type: integer
      required: true
    limit:
      in: query
      name: limit
      schema:
        type: integer
        default: 10
    page:
      in: query
      name: page
      schema:
        type: integer
        default: 1
  requestBodies:
    authSignIn:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                default: ""
              password:
                type: string
                default: ""
                minLength: 8
    cartCreate:
       content:
        application/json:
          schema:
            type: object
            properties:
               user_id:
                type: integer
                default: 1
               cart_items:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: integer
                      default: 0
                    quantity:
                      type: number
                      default: 0
    productCreate:
       content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                default: ""
              price:
                type: number
                default: 0
              description:
                type: string
                default: ""
    productUpdate:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                default: ""
              description:
                type: string
                default: ""
              price:
                type: number
                default: 0
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: OK
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: Bad Request
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: Unauthorized
    404:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: Not Found
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: Internal Server Error
    authSignIn:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  token:
                    type: string
                    default: ""
              message:
                type: string
                default: OK
    cartList:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    cartItems:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          product_id:
                            type: integer
                          quantity:
                            type: number
              message:
                type: string
                default: OK
              page:
                type: object
                properties:
                  current:
                    type: integer
                  size:
                    type: integer
                  total:
                    type: integer
    productDetail:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  created_at:
                    type: string
                    default: ""
                  description:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
                  price:
                    type: number
                    default: 0
              message:
                type: string
                default: OK
    productList:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    description:
                      type: string
                      default: ""
                    id:
                      type: integer
                    name:
                      type: string
                      default: ""
                    price:
                      type: number
                      default: 0
                    created_at:
                      type: string
                      default: ""
              message:
                type: string
                default: OK
              page:
                type: object
                properties:
                  current:
                    type: integer
                  size:
                    type: integer
                  total:
                    type: integer